name: Auto-approve Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto_approve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for Dependabot bump
        id: dependabot_bump
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q ".*dependabot.*"; then
            echo "::set-output name=approved::true"
          else
            echo "::set-output name=approved::false"
          fi

      - name: Approve pull request
        if: steps.dependabot_bump.outputs.approved == 'true'
        uses: peter-evans/approvals@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.number }}
